### ISSUE TITLE
無法讀取header footer 等

### ISSUE THREAD

**Issue by cheetosysst** [ckcsc-32nd/ckcsc-32nd.github.io#2]
rt，在本地使用時會無法引入，請改成同一個檔案

沒必要分成多個檔案，麻煩會多

**Comment by simba-fs** [comment]
你是說header和footer嗎？
如果不把它們拆出來，我只要改一個字就要每個檔案都改，不符合模組化設計
關於本地端裝Apache就解決了
我也是這麼用

**Comment by cheetosysst** [comment]
好吧 ，我只是覺的模組化很麻煩
